PR: PP pattern text updates
alphagov/verify-local-patterns pull request #657
Opened 2017-08-31 16:26 UTC by lizziebruce

Edits to pattern guidance based on @EUzkuraityte 's feedback. 

Some more issues still being discussed via https://docs.google.com/document/d/14kCKn2hc7_9rY5wz-9Djx9S47qWuga1LaIcQw8OXj5s/edit?ts=59a67fe4

2017-09-04 10:05 UTC, suryanaga requested changes

2017-09-04 10:05 UTC, suryanaga commented on app/views/service-patterns/parking-permit/awareness/code.html
> +	<a href="oldtext/oldcopy">previous copy</a>
What's this about? It's a broken link.

2017-09-04 13:08 UTC, lizziebruce commented on app/views/service-patterns/parking-permit/awareness/code.html
> +	<a href="oldtext/oldcopy">previous copy</a>
No, it's where I kept old copy from history to refer to which had been lost on an update. I will delete it once everything else has the okay.

2017-09-05 14:56 UTC, suryanaga approved these changes

2017-09-05 14:56 UTC, merged